# Generated by Django 4.1.7 on 2023-03-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='order number')),
                ('product', models.CharField(max_length=64, verbose_name='product')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Ordered')], default=1, verbose_name='status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='name')),
            ],
        ),
    ]
